sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t rsv7/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rsv7/docker-react npm run test -- --coverage
