sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t rsv7/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rsv7/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-291943785872"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

